server:
  port: 8080

spring:
  application:
    name: study-oss

  cloud:
    nacos:
      discovery:
        server-addr: nacos.gotostudy:8848

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


logging:
  config: classpath:logback-spring.xml

aliyun:
  oss:
    file:
      endpoint: oss-cn-hangzhou.aliyuncs.com
      keyid: LTAI5tA3AgDkUfGSu1f6B67e
      keysecret: ArUuw0uSM6ZRhY6kTpktHBuZYa0zEA
      bucketname: gotostudy

#开启熔断机制
feign:
  hystrix:
    enabled: true