kind: Deployment
apiVersion: apps/v1
metadata:
  name: study-gat
  namespace: gotostudy
  labels:
    app: study-gat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-gat
  template:
    metadata:
      labels:
        app: study-gat
    spec:
      containers:
        - name: study-gat
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$APP_NAME:$TAG_NAME
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: gotostudy-nginx
  namespace: gotostudy
  labels:
    app: study-gat
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 8003
  selector:
    app: study-gat
  type: NodePort
  sessionAffinity: None

