server:
  port: 8001

spring:
  application:
    name: study-cms

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gotostudy?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&serverTimezone=Asia/Shanghai
    username: root
    password: root

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.158.130:31414
        namespace: 42b17086-f346-41a5-8e00-a4001721b882

  redis:
    host: 192.168.158.130
    port: 32200
    database: 0
    timeout: 1800000

#    lettuce:
#      pool:
#        max-active: 20
#        max-wait: -1
#        max-idle: 5
#        min-idle: 0

logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml

  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

feign:
  hystrix:
    enabled: true

