kind: Deployment
apiVersion: apps/v1
metadata:
  name: study-vod
  namespace: gotostudy
  labels:
    app: study-vod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-vod
  template:
    metadata:
      labels:
        app: study-vod
    spec:
      containers:
        - name: study-vod
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - name: tcp-8160
              containerPort: 8160
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: study-vod
  namespace: gotostudy
  labels:
    app: study-vod
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 8160
      targetPort: 8160
      nodePort: 31009
  selector:
    app: study-vod
  type: NodePort
  sessionAffinity: None

