kind: Deployment
apiVersion: apps/v1
metadata:
  name: study-oss
  namespace: gotostudy
  labels:
    app: study-oss
spec:
  replicas: 1
  selector:
    matchLabels:
      app: study-oss
  template:
    metadata:
      labels:
        app: study-oss
    spec:
      containers:
        - name: study-oss
          image: $REGISTRY/$DOCKERHUB_NAMESPACE/$PROJECT_NAME:latest
          ports:
            - name: tcp-8080
              containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600

---

kind: Service
apiVersion: v1
metadata:
  name: study-oss
  namespace: gotostudy
  labels:
    app: study-oss
spec:
  ports:
    - name: http-80
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31006
  selector:
    app: study-oss
  type: NodePort
  sessionAffinity: None

